library civgen.globals;

Map<String, String> civMap = {
  'Theodore Roosevelt (RR)': 'America (RR)',
  'Theodore Roosevelt (BM)': 'America (BM)',
  'Saladin': 'Arabia',
  'John Curtin': 'Australia',
  'Montezuma': 'Aztec',
  'Hammurabi': 'Babylon',
  'Pedro II': 'Brazil',
  'Basil II': 'Byzantium',
  'Wilfrid Laurier': 'Canada',
  'Kublai Khan (C)': 'China',
  'Qin Shi Huang': 'China (QSH)',
  'Poundmaker': 'Cree',
  'Wilhelmina': 'Netherlands',
  'Cleopatra': 'Egypt',
  'Victoria': 'England (V)',
  'Eleanor': 'England (E)',
  'Menelik II': 'Ethiopia',
  'Catherine de Medici (BQ)': 'France',
  'Catherine de Medici (M)': 'France',
  'Ambiorix': 'Gallic',
  'Tamar': 'Georgia',
  'Frederick Barbarossa': 'Germany',
  'Simón Bolívar': 'Gran Colombia',
  'Pericles': 'Greece (P)',
  'Gorgo': 'Greece (G)',
  'Matthias Corvinus': 'Hungary',
  'Gandhi': 'India (G)',
  'Chandragupta': 'India (C)',
  'Hojo Tokimune': 'Japan',
  'Jayavarman VII': 'Khmer',
  'Mvemba a Nzinga': 'Kongo',
  'Seondeok': 'Korea',
  'Pachacuti': 'Inca',
  'Gitarja': 'Indonesia',
  'Alexander': 'Macedonia',
  'Mansa Musa': 'Mali',
  'Kupe': 'Māori',
  'Lautaro': 'Mapuche',
  'Lady Six Sky': 'Maya',
  'Genghis Khan (GK)': 'Mongolia',
  'Kublai Khan (KK)': 'Mongolia',
  'Harald Hardada': 'Norway',
  'Amanitore': 'Nubia',
  'Suleiman': 'Ottomans',
  'Cyrus': 'Persia',
  'Dido': 'Phoenicia',
  'Jadwiga': 'Poland',
  'João III': 'Portugal',
  'Trajan': 'Rome',
  'Peter': 'Russia',
  'Tomyris': 'Scythia',
  'Robert the Bruce': 'Scottland',
  'Philip II': 'Spain',
  'Kristina': 'Sweden',
  'Gilgamesh': 'Sumeria',
  'Bà Triệu': 'Vietnam',
  'Shaka': 'Zulu'
};
